### ISSUE TITLE
Vulkan SHADER_FLT32_ATOMIC error

### ISSUE THREAD

**Issue by Astatin3** [ArthurBrussee/brush#6]
Hello, This is a great project you have been working on! I hope all goes well with development.
I have unfortunately encountered a Vulkan error when I try to train the model, though the sparse reconstructing loading seems to go fine.
It may have to do with my linux installation, and I can't seem to find "naga::valid::Capabilities::SHADER_FLT32_ATOMIC" anywhere but in refrence to brush.

Rustc: `rustc 1.82.0 (f6e511eec 2024-10-15)`
cargo: `cargo 1.82.0 (8f40fc59f 2024-08-21)`
Linux: Debian Sid 6.11.4-amd64

Error:
```
(base) astatin3@acer:~/Documents/GitHub/brush$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/brush_bin`
[2024-10-25T15:30:15Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_support: Initialization of an object has failed

(brush_bin:35819): Gtk-WARNING **: 09:30:16.895: Failed to fetch network locations: The specified location is not mounted
"sparse/0/cameras.bin" "sparse/0/images.bin"
[2024-10-25T15:30:22Z ERROR wgpu_core::device::global] Device::create_shader_module error: 
    Shader validation error: 
    
    
[2024-10-25T15:30:22Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'async-std/runtime' panicked at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_shader_module
    
Shader validation error: 


      Type [12] '' is invalid
        Capability Capabilities(SHADER_FLT32_ATOMIC) is required


stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: wgpu::backend::wgpu_core::default_error_handler
             at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:3411:5
   3: core::ops::function::Fn::call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:79:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2245:9
   5: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:3397:17
   6: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error
             at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:296:9
   7: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::device_create_shader_module
             at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:931:17
   8: <T as wgpu::context::DynContext>::device_create_shader_module
             at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/context.rs:2236:37
   9: wgpu::Device::create_shader_module_unchecked
             at /home/astatin3/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/lib.rs:2905:26
  10: <cubecl_wgpu::compiler::wgsl::compiler::WgslCompiler as cubecl_wgpu::compiler::base::WgpuCompiler>::create_pipeline
             at /home/astatin3/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/3a4e3fb/crates/cubecl-wgpu/src/compiler/wgsl/compiler.rs:80:17
  11: cubecl_wgpu::compute::server::WgpuServer<C>::pipeline
             at /home/astatin3/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/3a4e3fb/crates/cubecl-wgpu/src/compute/server.rs:176:24
  12: <cubecl_wgpu::compute::server::WgpuServer<C> as cubecl_runtime::server::ComputeServer>::execute
             at /home/astatin3/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/3a4e3fb/crates/cubecl-wgpu/src/compute/server.rs:376:24
  13: <cubecl_runtime::channel::mutex::MutexComputeChannel<Server> as cubecl_runtime::channel::base::ComputeChannel<Server>>::execute
             at /home/astatin3/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/3a4e3fb/crates/cubecl-runtime/src/channel/mutex.rs:69:9
  14: cubecl_runtime::client::ComputeClient<Server,Channel>::execute_unchecked
             at /home/astatin3/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/3a4e3fb/crates/cubecl-runtime/src/client.rs:93:9
  15: <brush_render::render::RenderBackwards as burn_autodiff::ops::backward::Backward<burn_jit::backend::JitBackend<cubecl_wgpu::runtime::WgpuRuntime,f32,i32>,7_usize>>::backward::{{closure}}
             at ./crates/brush-render/src/render.rs:505:17
  16: tracing::span::Span::in_scope
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:1102:9
  17: <brush_render::render::RenderBackwards as burn_autodiff::ops::backward::Backward<burn_jit::backend::JitBackend<cubecl_wgpu::runtime::WgpuRuntime,f32,i32>,7_usize>>::backward
             at ./crates/brush-render/src/render.rs:504:13
  18: <burn_autodiff::ops::base::OpsStep<B,T,SB,_> as burn_autodiff::graph::base::Step>::step
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/ops/base.rs:256:9
  19: burn_autodiff::runtime::server::AutodiffServer::execute_steps::{{closure}}::{{closure}}
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/runtime/server.rs:89:34
  20: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:810:29
  21: <alloc::vec::into_iter::IntoIter<T,A> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/into_iter.rs:318:25
  22: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:813:9
  23: burn_autodiff::runtime::server::AutodiffServer::execute_steps::{{closure}}
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/runtime/server.rs:87:13
  24: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:810:29
  25: core::iter::traits::double_ended::DoubleEndedIterator::rfold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/double_ended.rs:308:21
  26: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/adapters/rev.rs:64:9
  27: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:813:9
  28: burn_autodiff::runtime::server::AutodiffServer::execute_steps
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/runtime/server.rs:86:9
  29: burn_autodiff::runtime::server::AutodiffServer::backward
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/runtime/server.rs:39:25
  30: <burn_autodiff::runtime::mutex::MutexClient as burn_autodiff::runtime::client::AutodiffClient>::backward
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/runtime/mutex.rs:40:20
  31: <burn_autodiff::backend::Autodiff<B,C> as burn_tensor::tensor::backend::base::AutodiffBackend>::backward
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-autodiff/src/backend.rs:64:9
  32: burn_tensor::tensor::api::autodiff::<impl burn_tensor::tensor::api::base::Tensor<B,_>>::backward
             at /home/astatin3/.cargo/git/checkouts/burn-467c12cab312d803/9bc3986/crates/burn-tensor/src/tensor/api/autodiff.rs:8:9
  33: brush_train::train::SplatTrainer<B>::step::{{closure}}::{{closure}}
             at ./crates/brush-train/src/train.rs:271:84
  34: tracing::span::Span::in_scope
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:1102:9
  35: brush_train::train::SplatTrainer<B>::step::{{closure}}
             at ./crates/brush-train/src/train.rs:271:25
  36: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  37: brush_viewer::train_loop::train_loop::{{closure}}::{{closure}}
             at ./crates/brush-viewer/src/train_loop.rs:153:26
  38: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
  39: futures_util::future::future::FutureExt::poll_unpin
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/future/future/mod.rs:558:9
  40: <async_fn_stream::TryFnStream<T,E,Fut> as futures_core::stream::Stream>::poll_next
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-fn-stream-0.2.2/src/lib.rs:173:17
  41: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.31/src/stream.rs:130:9
  42: <async_std::stream::stream::next::NextFuture<T> as core::future::future::Future>::poll
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/stream/stream/next.rs:17:9
  43: brush_viewer::viewer::process_loop::{{closure}}::{{closure}}
             at ./crates/brush-viewer/src/viewer.rs:131:53
  44: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
  45: futures_util::future::future::FutureExt::poll_unpin
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/future/future/mod.rs:558:9
  46: <async_fn_stream::TryFnStream<T,E,Fut> as futures_core::stream::Stream>::poll_next
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-fn-stream-0.2.2/src/lib.rs:173:17
  47: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.31/src/stream.rs:130:9
  48: <async_std::stream::stream::map::Map<S,F> as futures_core::stream::Stream>::poll_next
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/stream/stream/map.rs:36:41
  49: <async_std::stream::stream::next::NextFuture<T> as core::future::future::Future>::poll
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/stream/stream/next.rs:17:9
  50: brush_viewer::viewer::ViewerContext::start_data_load::{{closure}}
             at ./crates/brush-viewer/src/viewer.rs:208:47
  51: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/task/builder.rs:199:17
  52: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/task/task_locals_wrapper.rs:60:13
  53: std::thread::local::LocalKey<T>::try_with
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:283:12
  54: std::thread::local::LocalKey<T>::with
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260:9
  55: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/task/task_locals_wrapper.rs:55:9
  56: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.13.0/src/task/builder.rs:197:13
  57: async_executor::Executor::spawn_inner::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.13.1/src/lib.rs:250:20
  58: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.1/src/raw.rs:550:21
  59: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  60: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panic/unwind_safe.rs:272:9
  61: std::panicking::try::do_call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  62: __rust_try
  63: std::panicking::try
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  64: std::panic::catch_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  65: async_task::raw::RawTask<F,T,S,M>::run
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.1/src/raw.rs:549:23
  66: async_executor::State::run::{{closure}}::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.13.1/src/lib.rs:741:21
  67: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.3.0/src/future.rs:449:33
  68: async_executor::State::run::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.13.1/src/lib.rs:748:32
  69: async_executor::Executor::run::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.13.1/src/lib.rs:344:34
  70: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.3.0/src/future.rs:449:33
  71: async_io::driver::block_on::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-io-2.3.4/src/driver.rs:199:37
  72: std::thread::local::LocalKey<T>::try_with
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:283:12
  73: std::thread::local::LocalKey<T>::with
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260:9
  74: async_io::driver::block_on
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-io-2.3.4/src/driver.rs:175:5
  75: async_global_executor::reactor::block_on::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/reactor.rs:3:18
  76: async_global_executor::reactor::block_on
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/reactor.rs:12:5
  77: async_global_executor::threading::thread_main_loop::{{closure}}::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/threading.rs:95:17
  78: std::thread::local::LocalKey<T>::try_with
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:283:12
  79: std::thread::local::LocalKey<T>::with
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260:9
  80: async_global_executor::threading::thread_main_loop::{{closure}}
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/threading.rs:89:13
  81: std::panicking::try::do_call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  82: std::panicking::try
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  83: std::panic::catch_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  84: async_global_executor::threading::thread_main_loop
             at /home/astatin3/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/threading.rs:88:12
  85: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The very first `get_physical_device_surface_support` error is printed when the program starts up.

Here is the dataset, if you need it: https://drive.google.com/file/d/1G4kVD2tUKYBcXxK36TBFL9GQxEisfflw/view?usp=sharing

Thank you so much!

**Comment by ArthurBrussee** [comment]
Ah so I am using a custom branch of wgpu at the moment that add native  atomic float support. I _thought_ this was basically always supported on Vulkan, but maybe not! 

Can you try disabling it here: https://github.com/ArthurBrussee/brush/blob/7273fc00083baa94b3984abc07597ca65ef0d32e/crates/brush-render/src/render.rs#L502 ?

I should do a proper check there to see if it's supported - it's only a minor performance degradation if not.

**Comment by Astatin3** [comment]
I've changed the line to 
```
 let hard_float = !cfg!(target_family = "wasm") && !cfg!(target_os = "android") && !cfg!(target_os = "linux"); 
```
 The training seems to work now, but makes wayland lag for some reason, and it uses almost no system resources.

**Comment by AsherJingkongChen** [comment]
@ArthurBrussee 

The feature works on Windows Vulkan (NVIDIA RTX)

See gfx-rs/wgpu#6234

If you have found similar errors, welcome to feedback.
